Always require confirmation click when downloading LoginFile
nimiq/keyguard pull request #424
Opened 2021-03-29 11:21 UTC by sisou

Replaces #423.

2021-04-01 13:51 UTC, danimoh requested changes
- This PR does not implement the final design yet.
- `back-to-download` is still referenced in `Export.css` and can be removed.

2021-04-01 13:51 UTC, danimoh commented on src/components/DownloadLoginFile.js
>                  this.fire(DownloadLoginFile.Events.INITIATED);
This should now always be fired, which means the `if` condition can be removed.

2021-04-01 13:51 UTC, danimoh commented on src/components/DownloadLoginFile.js
>              // hash change is delayed by the .maybe-downloaded confirmation mechanism.
The comments in this method are not accurate anymore.

2021-04-01 13:51 UTC, danimoh commented on src/translations/fr.json
> +    "download-loginfile-successful": "Téléchargement réussi?",
This was not a typo.
French people apparently have a space before the question mark.
We're using non-breaking spaces to avoid breaking the question mark into the next line.

2021-04-01 13:51 UTC, danimoh commented on src/components/DownloadLoginFile.js
> +        this.$el.classList.add('maybe-downloaded');
The `maybe-downloaded` class is currently not being used anymore.

2021-04-03 17:37 UTC, mariofriz commented on src/translations/fr.json
> +    "download-loginfile-successful": "Téléchargement réussi?",
I can confirm there is a space in french before the ?

2021-04-04 00:28 UTC, Yukiioz commented on src/translations/fr.json
> +    "download-loginfile-successful": "Téléchargement réussi?",
Yes, there is one. And please use a non-breaking space for it :)

2021-04-06 10:55 UTC, sisou commented on src/components/DownloadLoginFile.js
> +        this.$el.classList.add('maybe-downloaded');
The class is now used again for changing the buttons in this state.

2021-04-07 11:40 UTC, Yukiioz approved these changes
Simple and effective. Nice 👍 
I would've loved to have a transition between the buttons, with the text fading out. But i guess that since we're opening a popup the "jump" is not meant to be seen so we don't really need one.

2021-04-14 23:22 UTC, danimoh approved these changes
Looks good.
I agree with Matheo that animating between the two states would be nice.
Note that not always a popup dialogue is opening, specifically if the user has his browser setup to download files immediately.
In this case he'd be seeing the animation.

For the `fallback-download` case I would personally not unveil the `Continue` text in the continue button as it breaks the layout to a degree.

2021-04-15 07:27 UTC, merged

2021-04-15 07:30 UTC, sisou commented
I created issue #426 for the button transitions, as it's too much work now to figure this out and not worth the delay in releasing this fix.