Multisig: Connect request and SignMultisigTransaction request
nimiq/keyguard pull request #458
Opened 2022-12-01 15:36 UTC by sisou

This PR adds two requests:
- Connect
- SignMultisigTransaction

## Connect

For this request, I am adding deterministic RSA key generation from the user's Key's `secret`. The public RSA key is then shared with the connected app, to be able to encrypt data that only the Keyguard can decrypt again. Encryption and decryption uses the `window.crypto.subtle` APIs.

## SignMultisigRequest

For this request, I am adding a WebAssembly file + JS loader, and the raw Rust code that produces it. This is needed as with the multisig scheme Nimiq is using, scalar multiplication is required, which we cannot do in Javascript. A minimal Rust crate does the trick, and is used as WASM when signing.

2022-12-01 15:46 UTC, sisou commented
@danimoh Do you maybe have a better idea of how to solve the double `KeyguardCommand.KeyguardCommand` in this commit?
https://github.com/nimiq/keyguard/pull/458/commits/253219009034c528395025c8d42168deade52d9c

2025-03-10 15:15 UTC, danimoh requested changes
In my opinion, quite a bit too many shortcuts have been taken, for example regarding missing i18n, unencrypted storage of private keys and omission of of relevant information in the UI.

There were also several serious security issues:
- generated RSA keys are orders of magnitude weaker than they should be, due to the way they are generated.
- (almost) arbitrary Nimiq messages are blindly signed, which can be used to impersonate the user.
- malicious apps are able to trick the Keyguard into storing and using RSA private keys known to them.

Additionally, this PR points out opportunities for further security hardening, code cleanup, code deduplication, smaller fixes, stricter parsing etc..

2025-03-10 15:15 UTC, danimoh commented on .eslintignore
> +src/lib/multisig/wasm/pkg
This folder has been removed again in fbbcf067a5043d9d56bd24c5a2ac79f63355fac1.

2025-03-10 15:15 UTC, danimoh commented on client/src/PublicRequest.ts
> +};
Could also be
```suggestion
export type SignMultisigTransactionRequestCommon = Transform<
    SignTransactionRequestCommon,
    'keyLabel' | 'senderLabel',
    Required<Pick<SignTransactionRequestCommon, 'keyLabel' | 'senderLabel'>>
> & {
    multisigConfig: MultisigConfig,
};
```
This ensures that there are no discrepancies if the original types of `keyLabel` or `senderLabel` were to change in `SignTransactionRequestCommon`, or if they were to be removed there. Obviously, in this case this benefit is of a rather theoretical nature. I just wanted to mention this alternative.

2025-03-10 15:15 UTC, danimoh commented on client/src/PublicRequest.ts
> +export type SignMultisigTransactionRequestLayout = 'standard';
Are you planning to add other layouts?

2025-03-10 15:15 UTC, danimoh commented on client/src/PublicRequest.ts
> +    T extends Is<T, SignMessageRequest> ? SignatureResult :
Should `SignMessageRequest` also receive an alias `SignMessageResult` for `SignatureResult`, similar to `SignMultisigTransactionResult`? Also in `RedirectResult` above and `ResultByCommand` below.

2025-03-10 15:15 UTC, danimoh commented on types/Keyguard.d.ts
> +}
Can be used as `KeyguardRequest.EncryptionKeyParams` without copying it from `PublicRequest.ts`.

```suggestion
type EncryptionKeyParams = KeyguardRequest.EncryptionKeyParams;
```

2025-03-10 15:15 UTC, danimoh commented on package.json
> +    "@nimiq/albatross-wasm": "https://gitpkg.now.sh/nimiq/core-rs-albatross/web-client/dist?06999e1626b3312a906a0a490339d7feb781811b",
Will the Multisig primitives eventually be added to the regular `@nimiq/core` package?

2025-03-10 15:15 UTC, danimoh commented on tsconfig.json
> +    "src/lib/multisig/wasm/pkg",
This folder has been removed again in fbbcf067a5043d9d56bd24c5a2ac79f63355fac1.

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/forge.min.js.map
Doesn't look like these mappings are very useful. (Even though they were taken directly from the `node-forge` package).

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/forge.min.js
For any other reviewer wondering: this is `forge.min.js` from `node-forge`  version 1.3.1 (sha256 dc67fd132427ad96c9666c844b39565413c40ddb1f2d063c53512fbf6d387dfd)

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.html
> +    <title>RSA Keys Iframe | Keyguard Demo</title>
It's not only used in the demos.
```suggestion
    <title>RSA Keys Iframe</title>
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    const bytes = /** @type {string} */ (forge.asn1.toDer(key).getBytes());
Can be typed more accurately, and I'd personally prefer `keyToArrayBuffer` as a name (do we do that anywhere else to appreviate To as 2?). Additionally, our APIs mostly work on Uint8Arrays, so I'd suggest `keyToUint8Array`:
```js
/**
 * @param {forge.asn1.Asn1} key
 * @returns {Uint8Array}
 */
function keyToUint8Array(key) {
    const bytes = forge.asn1.toDer(key).getBytes();
    const result = new Uint8Array(bytes.length);
    for (let i = 0; i < bytes.length; i++) {
        result[i] = bytes.charCodeAt(i);
    }
    return result;
}
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.html
> +</head>
We should add a CSP meta tag here which enforces the sandbox, even when not opened in the iframe it was designed for, and set the `frame-ancestors` to only the keyguard to disallow the page being embedded in other pages.

Generally, the CSP for this iframe can be very strict, for example:
```html
    <meta http-equiv="Content-Security-Policy" content="
        sandbox allow-scripts;
        frame-ancestors 'self';
        default-src 'none';
        script-src 'self';
    ">
```

However, unfortunately, `sandbox` and `frame-ancestors` do not seem to be allowed to be specified via the `meta` tag. So those should be configured on the server by @curdbecker.

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
The entire script should refuse running (e.g. by throwing immediately) if it's not inside an iframe or if it's not an iframe within the Keyguard. Otherwise, a malicious page can open the page as iframe (unless disallowed by an appropriate CSP) or as a popup (always possible, I think), and communicate with it.

```js
if (// Refuse to run if:
    // - Run as top level window
    window.self === window.top
    // - Iframe is embedded in another domain
    || window.location.origin !== new URL(document.referrer).origin
    // - Iframe can access parent page and is thus not sandboxed
    || !!window.frameElement
) throw new Error('Only allowed to run in a sandboxed iframe');
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    }
Where would such same-window events come from? Does `forge` send messages to the window itself?
(Mostly out of curiosity. Checking for it does no harm of course.)

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    }
Messages which are not coming from the Keyguard should be rejected.
```suggestion
    if (event.origin !== window.location.origin || !event.source) return; // Reject messages from other origins
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> + * @typedef {{command: 'generateKey', seed: string, keySize: number}} GenerateKeyCommand
The `seed` should be better a `Uint8Array` instead of a binary string because it's not very clear that a binary string is expected, and not for example hex encoded data, and binary strings just feel very outdated.
```suggestion
 * @typedef {{command: 'generateKey', seed: Uint8Array, keySize: number}} GenerateKeyCommand
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +        }
If not enough entropy was provided, we should throw and reject instead. The caller should make sure to provide enough entropy or stretch it out with a proper key derivation function, instead of us simply repeating the seed here.
```suggestion
        if (needed > seed.length) {
            throw new Error(`Seed does not provide enough entropy. ${needed} bytes needed`);
        }
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +        return seed.substring(0, needed);
There's no good reason to truncate the entropy if we have more than required, as whatever amount of entropy received [will be collected](https://github.com/digitalbazaar/forge/blob/a0a4a4264bedb3296974b9675349c9c190144aeb/lib/prng.js#L210).

Additionally, instead of truncating always to the first bytes of the entropy or returning the entire entropy, I was also thinking about returning a new slice of the entropy each time, because `forge.prng` does in fact [reseed for each generated random data](https://github.com/digitalbazaar/forge/blob/a0a4a4264bedb3296974b9675349c9c190144aeb/lib/prng.js#L90-L95). A quick experiment showed that a `forge.rsa.generateKeyPair` does in fact trigger two reseeds. Therefore one might consider returning two individual slices of `needed` bytes each, and overall requiring a seed of length `2 * needed`. However, looking at the linked comment, it seems like the frequent reseeding is mostly out of paranoia and not strictly required.

Overall, I would say returning the full, non-truncated seed in a single slice on all reseeds is a good middle ground.

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    // ));
> Sadly, those cannot be created in sandboxed iframes without `allow-same-origin`

Or luckily, because using webworkers could apparently cause the key generation to not be deterministic anymore: if a prng is passed, `generateKeyPair` uses a pure js implementation, which if async mode is enabled by passing a callback,  calls `_generateKeyPair`. `_generateKeyPair` in turn calls `prime.generateProbablePrime` which then calls `primeincFindPrime` and that calls `primeincFindPrimeWithWorkers` which features [the following comment](https://github.com/digitalbazaar/forge/blob/a0a4a4264bedb3296974b9675349c9c190144aeb/lib/prime.js#L150-L153):
```
// NOTE: This algorithm is indeterminate in nature because workers
// run in parallel looking at different segments of numbers. Even if this
// algorithm is run twice with the same input from a predictable RNG, it
// may produce different outputs.
```

Therefore, the async usage should be banned here.
```suggestion
    // Use the synchronous version of forge.rsa.generateKeyPair and not the asynchronous version with WebWorkers because
    // - WebWorkers cannot be created in sandboxed iframes without `allow-same-origin`:
    //   https://stackoverflow.com/a/30567964/4204380.
    // - Using multiple WebWorkers introduces race conditions, which causes the key generation to not be deterministic
    //   anymore, even if a deterministically seeded PRNG is used, see documentation on `primeincFindPrimeWithWorkers`:
    //   https://github.com/digitalbazaar/forge/blob/a0a4a4264bedb3296974b9675349c9c190144aeb/lib/prime.js#L150-L153
    //   If using WebWorkers, that method is called via `generateKeyPair` > `_generateKeyPair` > `generateProbablePrime`
    //   > `primeincFindPrime` > `primeincFindPrimeWithWorkers`.
    const keyPair = forge.pki.rsa.generateKeyPair({ bits: data.keySize, prng });
```

Unfortunately, this blocks the main thread in some browsers like Firefox, where same origin iframes are running on the same thread as the main window. In Chrome, [that is not the case](https://www.chromium.org/developers/design-documents/oop-iframes).

2025-03-10 15:15 UTC, danimoh commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    }, '*');
```suggestion
    /** @type {Window} */ (event.source).postMessage({
        privateKey: key2ArrayBuffer(privateKeyInfo),
        publicKey: key2ArrayBuffer(publicKeyInfo),
    }, window.location.origin);
```
Either only allow sending the response to known keyguard origins, or the same origin the iframe is running on (also the default if no target origin is specified but the sandbox is messing with that so our `location.origin` has to be specified manually).

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +    static _isEncryptionKeyParamsEqual(paramsA, paramsB) {
```suggestion
    /**
     * @private
     * @param {EncryptionKeyParams} paramsA
     * @param {EncryptionKeyParams} paramsB
     * @returns {boolean}
     */
    static _areEncryptionKeyParamsEqual(paramsA, paramsB) {
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +        this.rsaKeyPair = config.rsaKeyPair;
```suggestion
        this._rsaKeyPair = config.rsaKeyPair;
```
For consistency with other properties, the name should start with an underscore, and then a getter be added. Also, I would move the definition just below the definition of `_hasPin`, as it also belongs to the `config`.

Additonal getter:
```js
    /**
     * @returns {RsaKeyPairExport | undefined}
     */
    getRsaKeyPairExportIfExists() {
        return this._rsaKeyPair;
    }
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +        ]);
```suggestion
        const otherPublicKeys = otherSigners.map(({ publicKey }) => publicKey);
        const otherCommitments = otherSigners.map(({ commitments }) => commitments);
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +    static _isDefaultEncryptionKeyParams(params) {
```suggestion
    /**
     * @private
     * @param {EncryptionKeyParams} params
     * @returns {boolean}
     */
    static _areDefaultEncryptionKeyParams(params) {
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +        }
This little snippet could be deduplicated into a method `setRsaKeyPair`.
```suggestion
        const rsaKeyPair = await this.setRsaKeyPair(keyParams);
```

With method:
```js
    /**
     * Calculates and sets the RSA key pair for the given key params. The RSA key is calculated deterministically based
     * on _secret, such that the same RSA key is generated for the same key params.
     * Warning: this method is computationally expensive.
     * @param {EncryptionKeyParams} keyParams
     * @returns {Promise<RsaKeyPairExport>}
     */
    async setRsaKeyPair(keyParams) {
        if (!this._rsaKeyPair || !Key._areEncryptionKeyParamsEqual(keyParams, this._rsaKeyPair.keyParams)) {
            this._rsaKeyPair = await this._computeRsaKeyPair(keyParams);
            if (Key._areDefaultEncryptionKeyParams(keyParams)) {
                await KeyStore.instance.setRsaKeypair(this.id, this._rsaKeyPair);
            }
        }
        return this._rsaKeyPair;
    }
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +        const iframe = document.createElement('iframe');
Would be good to add a comment that explains why we're doing all this fun with the iframe, i.e. browser APIs don't support the deterministic generation of RSA keys from a seed, therefore we use a library, but to avoid an increased attack surface by including a library not audited by us, we run it in a sandbox.
```suggestion
        // Setup the RSAKeysIframe in which the actual computation of the RSA key happens via node-forge. The reason why
        // we don't use the browser crypto API instead, is that it does not support deterministic generation of RSA keys
        // from an existing secret, and the reason why node-forge is not used directly here is that we want to run it in
        // a sandbox, to reduce the attack surface from a big external dependency, not thoroughly audited by us.
        const iframe = document.createElement('iframe');
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +        const loadPromise = new Promise(resolve => iframe.addEventListener('load', () => resolve()));
```suggestion
        const loadPromise = new Promise(resolve => iframe.addEventListener('load', resolve));
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +            seed: Nimiq.BufferUtils.toUtf8(seed), // seed is a bytestring
This is a very bad idea, and a security issue.

This interprets the bytes as UTF8 encoding and decodes it to a Javascript string, which is UTF16 encoded. Up to 4 UTF8 bytes can represent a single unicode symbol, which is then encoded as a single UTF16 character or a UTF16 surrogate pair. The following re-encodings are possible:
1 UTF8 byte -> 1 UTF16 character
2 UTF8 bytes -> 1 UTF16 character
3 UTF8 bytes -> 1 UTF16 character
4 UTF8 bytes -> 2 UTF16 characters (surrogate pair)

This means that the resulting string can be as short as a third of the length of the input byte array. As `node-forge` expects a binary string as input, where each character is interpreted as a single byte, overall in the worst case, two thirds of the original data are discarded and an exponentially weaker entropy is used.

Note that fixing this is a breaking change, as the resulting RSA key will be different. Therefore, users who already have a stored RSA key need to logout to clear their old RSA key (or we rename the property in the store). The multisig app must then discard its known RSA public keys and associated encrypted secrets, and connect the account again to get the new RSA public key.

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +        return resultPromise;
I think the Promise reads nicer like this:
```suggestion
        return new Promise(resolve => {
            /**
             * @param {MessageEvent} event
             */
            function onMessage(event) {
                if (event.source === event.target) {
                    // console.log("Ignored same-window event:", event);
                    return;
                }

                /** @type {{privateKey: ArrayBuffer, publicKey: ArrayBuffer}} */
                const data = event.data;
                if (!('privateKey' in data) || !('publicKey' in data)) return;

                window.removeEventListener('message', onMessage);

                resolve({
                    privateKey: new Uint8Array(data.privateKey),
                    publicKey: new Uint8Array(data.publicKey),
                    keyParams,
                });
            }

            // Listen for result from iframe
            window.addEventListener('message', onMessage);
        });
```

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +        }, '*');
Might want to add a comment that due to the iframe's sandboxed origin, we can't be more restrictive than `'*'`.

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +            }
Here, we absolutely must check that the message came from the iframe, otherwise the following attack is possible:
A malicious site starts a `Connect` request in an iframe (via Hub, which then redirects to the Keyguard). Then, when the malicious site suspects that the the Keyguard is waiting for the RSA key calculation, it itself sends a postmessage to the popup with an RSA key known to the attacker, which the Keyguard would willingly store and continue to use, also for other websites.

2025-03-10 15:15 UTC, danimoh commented on src/lib/Key.js
> +            window.removeEventListener('message', onMessage);
At this point, also the iframe should be removed from the DOM, such that it can be garbage collected.

2025-03-10 15:15 UTC, danimoh commented on src/lib/KeyStore.js
> +            rsaKeyPair: key.rsaKeyPair,
I think if the key is password encrypted, we should encrypt the rsa key as well. Same in setRsaKeypair.

2025-03-10 15:15 UTC, danimoh commented on src/lib/RequestParser.js
> +            throw new Errors.InvalidRequestError('Request must be an object');
```suggestion
        if (!object || typeof object !== 'object') {
            throw new Errors.InvalidRequestError('Transaction info must be an object');
```

- The `object === null` check is already covered by `!object`.
- The transaction is being parsed here, not the entire request.

2025-03-10 15:15 UTC, danimoh commented on tests/lib/RequestParser.spec.js
> +        expect(requestParser.parseLogoUrl(undefined, true, 'shopLogoUrl')).toBe(undefined);
A test could be added here to test the `false` for the newly introduced `allowEmpty`.

2025-03-10 15:15 UTC, danimoh commented on tests/lib/Key.spec.js
> +    // })
TODO

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/index.html
> +                </span>
Missing i18n.

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/index.html
> +                    Your funds remain unaffected.
Missing i18n.

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/index.html
> +                <form id="password-box" class=""></form>
Empty `class` can be removed.

```suggestion
                <form id="password-box"></form>
```

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/ConnectApi.js
> +];
Should some of the new commands like `sign-staking` or `sign-polygon-transaction` be added?

```suggestion
const PermissionKeyguardCommands = [
    /** @type {KeyguardCommand.KeyguardCommand} */ ('remove-key'),
    /** @type {KeyguardCommand.KeyguardCommand} */ ('export'),
    /** @type {KeyguardCommand.KeyguardCommand} */ ('change-password'),
    // /** @type {KeyguardCommand.KeyguardCommand} */ ('sign-transaction'), // Already third-party whitelisted in Hub
    /** @type {KeyguardCommand.KeyguardCommand} */ ('sign-multisig-transaction'),
    // /** @type {KeyguardCommand.KeyguardCommand} */ ('sign-staking'), // Already third-party whitelisted in Hub
    // /** @type {KeyguardCommand.KeyguardCommand} */ ('sign-message'), // Already third-party whitelisted in Hub
    /** @type {KeyguardCommand.KeyguardCommand} */ ('derive-address'),
    // Bitcoin
    /** @type {KeyguardCommand.KeyguardCommand} */ ('sign-btc-transaction'),
    /** @type {KeyguardCommand.KeyguardCommand} */ ('derive-btc-xpub'),
    // Polygon
    /** @type {KeyguardCommand.KeyguardCommand} */ ('sign-polygon-transaction'),
    /** @type {KeyguardCommand.KeyguardCommand} */ ('derive-polygon-address'),
    // Swap
    /** @type {KeyguardCommand.KeyguardCommand} */ ('sign-swap'),
];
```

2025-03-10 15:15 UTC, danimoh commented on types/KeyguardCommand.d.ts
> +export = _KeyguardCommand;
Could be nice to actually reimplement the enum from the client in the Keyguard's js.

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/index.html
> +                <button data-i18n="passwordbox-connect-account" class="nq-button light-blue continue display-none">Connect your account</button>
Unused button

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/Connect.js
> +        });
Unused event handler for unused buton.

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/Connect.js
> +            reject(new Errors.CoreError(errorMessage));
```suggestion
            reject(new Errors.CoreError(error instanceof Error ? error : errorMessage));
```
Passing the original error preserves the stack trace.

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/Connect.js
> +            const signature = key.signMessage(keyPath, messageBytes);
This blindly signs any arbitrary text message as a valid Nimiq message signature. I.e. an attacker can trick the user into unknowingly signing messages with the only restriction enforced by request parsing being that the message must be textual, which is the most common case for messages to be approved by the user. This can for example be abused to authenticate at staking pool websites as the user.

To avoid this, a prefix separate to the Nimiq message signature prefix should be used, for example `\x18Nimiq Signed Challenge:\n` (in contrast to `\x16Nimiq Signed Message:\n` used for Nimiq messages).
Alternatively, the challenge can still be signed as a Nimiq message, but with an additional prefix enforced on the challenge. A separate prefix is arguably more elegant.

This is a breaking change, which also requires adaptions in apps using the Connect request.

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/index.html
> +                                The first address of your account will be visible to all participants in your shared wallet.
Not the first address but the addresses for the `requestedKeyPaths`.

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/ConnectApi.js
> +        );
This can be abused by a malicious app to silently learn any number of the user's addresses. Those should probably be shown in the UI.

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/Connect.js
> +        const keyParams = /** @type {RsaKeyPairExport} */ (key.rsaKeyPair).keyParams;
```suggestion
        const keyParams = Key.defaultEncryptionKeyParams;
        const rsaPublicCryptoKey = await key.getRsaPublicKey(keyParams);
```

2025-03-10 15:15 UTC, danimoh commented on src/request/connect/Connect.js
> +                algorithm: { name: 'RSA-OAEP', hash: 'SHA-256' },
Can read algorithm from `rsaPublicCryptoKey.algorithm` instead of hard coding the constant here.

```suggestion
                algorithm: {
                    name: rsaPublicCryptoKey.algorithm.name,
                    hash: (/** @type {RsaHashedKeyAlgorithm} */ (rsaPublicCryptoKey.algorithm)).hash.name,
                },
```

2025-03-10 15:15 UTC, danimoh commented on client/src/PublicRequest.ts
> +    permissions: KeyguardCommand[],
The permissions are not currently processed in a meaningful fashion. Neither are they displayed to the user, nor are they persisted or checked for. Therefore, this should be removed for now.

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/index.html
> +    <link rel="stylesheet" href="SignMultisigTransaction.css">
`CurrencyInfo.js` and `FiatApi.js` are probably not necessary to be included.

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/index.html
> +                    </div>
The structure of these sentences could be entirely different in other languages, and also the little text segments do not provide enough context to the translators of what the complete sentence will be in the end. Therefore, this should be complete texts with placeholders, which are then later replaced in Javascript and assembled as DOM elements.

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/index.html
> +            </g></svg>
Could apply the same little optimization from 3b69993e here, too. Equally in `connect/index.html`.

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransaction.css
> +}
This entire section is almost identical to `SignTransaction.css`. Thus, that one should simply be imported instead of duplicating everything.

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransaction.css
> +    margin-bottom: -0.5rem;
```suggestion
    margin: 0 -2rem -0.5rem;
```

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +        if (!object || typeof object !== 'object' || object === null) {
```suggestion
        if (!object || typeof object !== 'object') {
```

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +        } else if ('encrypted' in object.secrets) {
```suggestion
        } else if (object.secrets && typeof object.secrets === 'object' && 'encrypted' in object.secrets && 'keyParams' in object.secrets) {
```

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +            );
If `secret` cannot be deserialized as a valid `RandomSecret`, the error is not mapped to a`InvalidRequestError`.
```suggestion
            try {
                for (const secret of object.secrets) {
                    if (!(secret instanceof Uint8Array)) throw new Error('must be Uint8Arrays');
                    secrets.push(new Nimiq.RandomSecret(secret));
                }
            } catch (error) {
                const errorMessage = error instanceof Error ? error.message : String(error);
                throw new Errors.InvalidRequestError(`Invalid secrets: ${errorMessage}`);
            }
```

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +            }
The length check is somewhat unnecessary and also not done above for unencrypted secrets.
Instead, a more sound check would be for `SignTransaction` to check that the number of my commitments, which it identifies after deriving my public key, matches the number of my secrets, which it currently doesn't do. If it would do that, no further check would be required that it should be at least two, because the commitments were all already checked to be at least two.

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +                throw new Errors.InvalidRequestError('Missing secrets.keyParams');
```suggestion
            if (!object.secrets.keyParams || typeof object.secrets.keyParams !== 'object') {
                throw new Errors.InvalidRequestError('Invalid secrets.keyParams');
```

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +        );
This limits the Multisig support to k of n Multisigs, where each combination of signers which can sign together has identical size k and draws from the n public keys. More advanced combinations are not supported, for example of varying size, e.g. a Multisig which can be signed by single master key A, or keys B and C combined, or combinations with no overlap. But that's fine. If ever needed, support for such can be added in the future by instead of passing the `publicKeys`, passing something like `publicKeyCombinations`.
Maybe some documentation should be added to `PublicRequestTypes` explaining what the publicKeys represent (i.e. the n public keys of a k of n multisig, and not aggregated public keys calculated over pre-determined combinations), and that only k of n Multisigs are supported currently.

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +        }
More concise and with documentation:
```suggestion
        if (!(transaction.senderType === Nimiq.AccountType.Basic && transaction.sender.equals(multisigAddress))
            // Vesting contracts owned by the multisig are allowed to send anywhere. The contract address can't be
            // verified here, it can however be assumed to be owned by the multisig, as only the owner can sign a valid
            // vesting withdrawal transaction.
            && transaction.senderType !== Nimiq.AccountType.Vesting
            // For other transactions which are not from a basic account, i.e. from a contract (other than a vesting
            // contract), we enforce the multisig to be the recipient. E.g. unstaking, HTLC refund, HTLC withdrawal etc.
            // are only allowed to the multisig address.
            && !(transaction.recipientType === Nimiq.AccountType.Basic && transaction.recipient.equals(multisigAddress))
        ) {
            throw new Errors.InvalidRequestError(
                'The transaction must either be send from or to the multisig, or from a vesting contract owned by it',
            );
        }
```

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransaction.js
> +            $loginFileIcon.innerHTML = ''; // Remove LoginFile icon
The HTML element is already empty.

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransaction.js
> +        }
The `for` loop can be deduplicated by first collecting only the `secrets` in the `if ... else ...` block, and doing the loop afterwards.
```suggestion
        /** @type {Nimiq.RandomSecret[]} */
        let ownCommitmentSecrets;
        if (Array.isArray(request.multisigConfig.secrets)) {
            ownCommitmentSecrets = request.multisigConfig.secrets;
        } else {
            // If we only have encrypted secrets, decrypt them first
            const rsaKey = await key.getRsaPrivateKey(request.multisigConfig.secrets.keyParams);

            try {
                ownCommitmentSecrets = await Promise.all(request.multisigConfig.secrets.encrypted.map(
                    async encrypted => new Nimiq.RandomSecret(new Uint8Array(
                        await window.crypto.subtle.decrypt(rsaKey.algorithm, rsaKey, encrypted),
                    )),
                ));
            } catch (error) {
                const errorMessage = error instanceof Error ? error.message : String(error);
                reject(new Errors.InvalidRequestError(`Cannot decrypt secrets: ${errorMessage}`));
                return;
            }
        }
        /** @type {Nimiq.CommitmentPair[]} */
        const ownCommitmentPairs = [];
        for (let i = 0; i < ownCommitmentSecrets.length; i++) {
            ownCommitmentPairs.push(new Nimiq.CommitmentPair(
                ownCommitmentSecrets[i],
                ownSigner.commitments[i],
            ));
        }
```

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransaction.js
> +        });
If the multisig is the recipient instead of the sender, the `multisig` property should be on the `_recipientAddressInfo`.

2025-03-10 15:15 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransaction.js
> +            // return ...
Even if not fully decoding the transaction data, it should at least hint at this being an interaction with a contract, be it contract creation, withdrawal, staking etc, based on sender and recipient type. Also even if there is no recipient data present.

2025-03-10 15:15 UTC, danimoh commented on src/components/AddressInfo.js
> +                <span class="of">of</span>
Missing i18n.

2025-03-10 15:15 UTC, danimoh commented on src/components/AddressInfo.css
> +    word-spacing: -0.071428571em; // 1/14
Invalid CSS comment (should be `/* 1/14 */`). But probably better as `calc(-1em / 14)` anyways.
```suggestion
    word-spacing: calc(-1em / 14);
```

2025-03-10 15:15 UTC, danimoh commented on src/components/LoginFileAccountIcon.js
> +     * @param {string} [address]
Why is the address allowed to be `undefined`? It's nowhere used in such a fashion.

2025-03-10 15:15 UTC, danimoh commented on tools/build.sh
> +cp -v src/lib/rsa/sandboxed/* dist/lib/rsa/sandboxed/
Integrity hashes on the js files would be good.

2025-03-10 15:15 UTC, danimoh commented on demos/index.html
> +<div><a href="/demos/ConnectAccount.html">Connect Account</a></div>
These demos don't work currently.

2025-03-10 15:17 UTC, danimoh requested changes
In my opinion, quite a bit too many shortcuts have been taken, for example regarding missing i18n, unencrypted storage of private keys and omission of of relevant information in the UI.

There were also several serious security issues:
- generated RSA keys are orders of magnitude weaker than they should be, due to the way they are generated.
- (almost) arbitrary Nimiq messages are blindly signed, which can be used to impersonate the user.
- malicious apps are able to trick the Keyguard into storing and using RSA private keys known to them.

Additionally, this PR points out opportunities for further security hardening, code cleanup, code deduplication, smaller fixes, stricter parsing etc..

2025-03-17 13:59 UTC, danimoh commented
> @danimoh Do you maybe have a better idea of how to solve the double KeyguardCommand.KeyguardCommand in this commit?
> https://github.com/nimiq/keyguard/commit/253219009034c528395025c8d42168deade52d9c

I tried multiple approaches.
Actually, the nested namespace can be avoided as easily as this:
```typescript
import { KeyguardCommand as _KeyguardCommand } from '../client/src/KeyguardCommand';

export as namespace KeyguardCommand;
export = _KeyguardCommand;
```

But that also occurred to me only later, and I think the approach that I took instead, which is replicating the client enums on the Javascript side of the Keyguard, is eventually nicer. This way, the enums are also usable in the Javascript in a type safe manner, without requiring any type assertions.

I first implemented the replicated enum in https://github.com/nimiq/keyguard/pull/524/commits/1f16c3d10dd181bedc6b164f07e6d747b03352a8, but then simplified / refined the approach in https://github.com/nimiq/keyguard/pull/524/commits/ea4bebed766669a1c949b38c813c7be3e7bbdcff. Both replication solutions are fully type checked and ensure equality with the original enum.

2025-07-02 12:15 UTC, sisou commented on client/src/PublicRequest.ts
> +};
Resolved in #524

2025-07-02 12:16 UTC, sisou commented on types/Keyguard.d.ts
> +}
Resolved in #524

2025-07-02 12:16 UTC, sisou commented on package.json
> +    "@nimiq/albatross-wasm": "https://gitpkg.now.sh/nimiq/core-rs-albatross/web-client/dist?06999e1626b3312a906a0a490339d7feb781811b",
Yes, and this PR has been updated to use a regular released package version.

2025-07-02 12:17 UTC, sisou commented on client/src/PublicRequest.ts
> +export type SignMultisigTransactionRequestLayout = 'standard';
Who knows? This just keeps the option open.

2025-07-02 12:18 UTC, sisou commented on src/lib/rsa/sandboxed/forge.min.js.map
Resolved in #524

2025-07-02 12:19 UTC, sisou commented on src/lib/rsa/sandboxed/forge.min.js
I added a check for exactly this hash in the build script in #532

2025-07-02 12:19 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.html
> +    <title>RSA Keys Iframe | Keyguard Demo</title>
Resolved in #524

2025-07-02 12:19 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    const bytes = /** @type {string} */ (forge.asn1.toDer(key).getBytes());
Resolved in #524

2025-07-02 12:20 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.html
> +</head>
Resolved in #524

2025-07-02 12:20 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
Resolved in #524

2025-07-02 12:21 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    }
I think browser extensions could trigger these.

2025-07-02 12:23 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    }
I re-added the check in #532, after it was removed in #524.

2025-07-02 12:24 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    }
Resolved in #524

2025-07-02 12:24 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> + * @typedef {{command: 'generateKey', seed: string, keySize: number}} GenerateKeyCommand
Resolved in #524

2025-07-02 12:25 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +        }
Resolved in #524

2025-07-02 12:25 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +        return seed.substring(0, needed);
Resolved in #524

2025-07-02 12:26 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    // ));
Resolved in #524

2025-07-02 12:26 UTC, sisou commented on src/lib/rsa/sandboxed/RSAKeysIframe.js
> +    }, '*');
Resolved in #524

2025-07-02 12:27 UTC, sisou commented on src/lib/Key.js
> +    static _isEncryptionKeyParamsEqual(paramsA, paramsB) {
Resolved in #524

2025-07-02 12:27 UTC, sisou commented on src/lib/Key.js
> +        this.rsaKeyPair = config.rsaKeyPair;
Resolved in #524

2025-07-02 12:28 UTC, sisou commented on src/lib/Key.js
> +        ]);
Resolved in #524

2025-07-02 12:28 UTC, sisou commented on src/lib/Key.js
> +    static _isDefaultEncryptionKeyParams(params) {
Resolved in #524

2025-07-02 12:28 UTC, sisou commented on src/lib/Key.js
> +        }
Resolved in #524

2025-07-02 12:28 UTC, sisou commented on src/lib/Key.js
> +        const iframe = document.createElement('iframe');
Resolved in #524

2025-07-02 12:29 UTC, sisou commented on src/lib/Key.js
> +        const loadPromise = new Promise(resolve => iframe.addEventListener('load', () => resolve()));
Resolved in #524

2025-07-02 12:29 UTC, sisou commented on src/lib/Key.js
> +            seed: Nimiq.BufferUtils.toUtf8(seed), // seed is a bytestring
Resolved in #524

2025-07-02 12:29 UTC, sisou commented on src/lib/Key.js
> +        return resultPromise;
Resolved in #524

2025-07-02 12:29 UTC, sisou commented on src/lib/Key.js
> +        }, '*');
Resolved in #524

2025-07-02 12:30 UTC, sisou commented on src/lib/Key.js
> +            }
Resolved in #524

2025-07-02 12:30 UTC, sisou commented on src/lib/Key.js
> +            window.removeEventListener('message', onMessage);
Resolved in #524

2025-07-02 12:31 UTC, sisou commented on src/lib/KeyStore.js
> +            rsaKeyPair: key.rsaKeyPair,
Resolved in #524 & #526

2025-07-02 12:32 UTC, sisou commented on src/lib/RequestParser.js
> +            throw new Errors.InvalidRequestError('Request must be an object');
Resolved in #524

2025-07-02 12:34 UTC, sisou commented on src/request/connect/index.html
> +                </span>
Resolved in #524

2025-07-02 12:34 UTC, sisou commented on src/request/connect/index.html
> +                    Your funds remain unaffected.
Resolved in #524

2025-07-02 12:35 UTC, sisou commented on src/request/connect/index.html
> +                <form id="password-box" class=""></form>
Resolved in #524

2025-07-02 12:35 UTC, sisou commented on src/request/connect/ConnectApi.js
> +];
Resolved in #524

2025-07-02 12:36 UTC, sisou commented on types/KeyguardCommand.d.ts
> +export = _KeyguardCommand;
Resolved in #524

2025-07-02 12:37 UTC, sisou commented on src/request/connect/index.html
> +                <button data-i18n="passwordbox-connect-account" class="nq-button light-blue continue display-none">Connect your account</button>
Resolved in #524

2025-07-02 12:37 UTC, sisou commented on src/request/connect/Connect.js
> +        });
Resolved in #524

2025-07-02 12:37 UTC, sisou commented on src/request/connect/Connect.js
> +            reject(new Errors.CoreError(errorMessage));
Resolved in #524

2025-07-02 12:37 UTC, sisou commented on src/request/connect/Connect.js
> +            const signature = key.signMessage(keyPath, messageBytes);
Resolved in #524

2025-07-02 12:37 UTC, sisou commented on src/request/connect/index.html
> +                                The first address of your account will be visible to all participants in your shared wallet.
Resolved in #524

2025-07-02 12:38 UTC, sisou commented on src/request/connect/ConnectApi.js
> +        );
Resolved in #524

2025-07-02 12:38 UTC, sisou commented on src/request/connect/Connect.js
> +        const keyParams = /** @type {RsaKeyPairExport} */ (key.rsaKeyPair).keyParams;
Resolved in #524

2025-07-02 12:38 UTC, sisou commented on src/request/connect/Connect.js
> +                algorithm: { name: 'RSA-OAEP', hash: 'SHA-256' },
Resolved in #524

2025-07-02 12:38 UTC, sisou commented on client/src/PublicRequest.ts
> +    permissions: KeyguardCommand[],
They are processed, stored, and checked in the Hub.

2025-07-02 12:39 UTC, sisou commented on src/request/sign-multisig-transaction/index.html
> +    <link rel="stylesheet" href="SignMultisigTransaction.css">
Resolved in #524

2025-07-02 12:39 UTC, sisou commented on src/request/sign-multisig-transaction/index.html
> +            </g></svg>
Resolved in #524

2025-07-02 12:39 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransaction.css
> +}
Resolved in #524

2025-07-02 12:40 UTC, sisou commented on src/request/sign-multisig-transaction/index.html
> +                    </div>
Resolved in #524

2025-07-02 12:40 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransaction.css
> +    margin-bottom: -0.5rem;
Resolved in #524

2025-07-02 12:41 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +        if (!object || typeof object !== 'object' || object === null) {
Resolved in #524

2025-07-02 12:42 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +        } else if ('encrypted' in object.secrets) {
Resolved in #524

2025-07-02 12:42 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +            );
Resolved in #524

2025-07-02 12:43 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +            }
But the check against the number of commitments only happens after password entering, whereas this check happens at the start of the request. The earlier the better.

2025-07-02 12:43 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +                throw new Errors.InvalidRequestError('Missing secrets.keyParams');
Resolved in #524

2025-07-02 12:44 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +        );
Resolved in #524

2025-07-02 12:45 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +        }
I do not agree with the more concise version, its not understandable. The documentation can also be added to the more verbose layout.

2025-07-02 12:45 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransaction.js
> +            $loginFileIcon.innerHTML = ''; // Remove LoginFile icon
Resolved in #524

2025-07-02 12:46 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransaction.js
> +        }
Resolved in #524

2025-07-02 12:46 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransaction.js
> +        });
Resolved in #524

2025-07-02 12:46 UTC, sisou commented on src/request/sign-multisig-transaction/SignMultisigTransaction.js
> +            // return ...
Resolved in #524

2025-07-02 12:46 UTC, sisou commented on src/components/AddressInfo.js
> +                <span class="of">of</span>
Resolved in #524

2025-07-02 12:46 UTC, sisou commented on src/components/AddressInfo.css
> +    word-spacing: -0.071428571em; // 1/14
Resolved in #524

2025-07-02 12:47 UTC, sisou commented on src/components/LoginFileAccountIcon.js
> +     * @param {string} [address]
Resolved in #524

2025-07-02 12:47 UTC, sisou commented on tools/build.sh
> +cp -v src/lib/rsa/sandboxed/* dist/lib/rsa/sandboxed/
Resolved in #524

2025-07-02 12:51 UTC, sisou commented on client/src/PublicRequest.ts
> +    T extends Is<T, SignMessageRequest> ? SignatureResult :
No, instead I'll remove `SignMultisigTransactionResult` and type the result as `SignatureResult` instead to keep it simple.

2025-07-02 13:29 UTC, sisou commented on tests/lib/RequestParser.spec.js
> +        expect(requestParser.parseLogoUrl(undefined, true, 'shopLogoUrl')).toBe(undefined);
Added in #532

2025-07-02 13:58 UTC, sisou commented on tests/lib/Key.spec.js
> +    // })
Fixed and re-enabled in #532

2025-07-02 15:24 UTC, sisou commented on demos/index.html
> +<div><a href="/demos/ConnectAccount.html">Connect Account</a></div>
Fixed in #532

2025-07-02 22:11 UTC, danimoh commented on client/src/PublicRequest.ts
> +    permissions: KeyguardCommand[],
But if the Hub is doing it, still this code does not need to be in Keyguard, because the Keyguard is not doing any of it.

2025-07-02 22:19 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +            }
There is not really an advantage in an early check. The check is to protect from invalid or malicious requests. In production, a working app should not be issuing invalid requests. During development, the dev might encounter the error during testing, and in that case indeed only after password entry, but for the dev that's fine. He is supposed to fix the issue after encountering it once. As for malicious requests, as the request is still eventually rejected, there is nothing to be gained, such that a malicious request for this error is also not to be expected in production.
I.e. for production, the additional, early check just bloats the code.

2025-07-02 22:26 UTC, danimoh commented on src/request/sign-multisig-transaction/SignMultisigTransactionApi.js
> +        }
I think the more concise version is actually better to understand, which is why I changed it. It clearly lists the acceptable cases, and does not mix acceptable and unacceptable cases.

2025-07-06 12:28 UTC, merged